packages:
  - packages/*
  - examples/*

catalog:
  "@biomejs/biome": ^2.2.7
  "@changesets/cli": latest
  "@custom-elements-manifest/analyzer": ^0.10.4
  "@storybook/addon-essentials": ^8.6.4
  "@storybook/blocks": ^8.6.4
  "@storybook/csf": ^0.1.13
  "@storybook/types": ^8.6.4
  "@storybook/web-components": ^8.6.4
  "@storybook/web-components-vite": ^8.6.4
  "@types/gapi": ^0.0.47
  "@types/google.accounts": ^0.0.15
  "@types/google.picker": ^0.0.49
  "@types/mdast": ^4.0.4
  "@types/mocha": ^10.0.10
  "@types/node": latest
  "@types/unist": ^3.0.3
  "@types/react": ^19.2.0
  "@types/react-dom": ^19.2.0
  browserslist: ^4.28.0
  browserslist-to-esbuild: ^2.1.1
  bundlewatch: ^0.4.0
  custom-elements-manifest: ^2.1.0
  husky: latest
  lint-staged: latest
  mdast-util-from-markdown: ^2.0.2
  prettier: ^3.5.3
  react: ^19.2.0
  react-dom: ^19.2.0
  remark: ^15.0.1
  remark-behead: ^3.1.0
  remark-gfm: ^4.0.1
  remark-github: ^12.0.0
  remark-toc: ^9.0.0
  storybook: ^8.6.4
  tsup: ^8.4.0
  tsx: ^4.19.3
  turbo: latest
  typescript: latest

onlyBuiltDependencies:
  - esbuild
